// KQL script
// Use management commands in this script to configure your database items, such as tables, functions, materialized views, and more.


.create-merge table AllSparkLogs (timestamp:datetime, category:string, fabricLivyId:string, applicationId:string, applicationName:string, executorId:string, userId:string, fabricTenantId:string, capacityId:string, artifactType:string, artifactId:string, fabricWorkspaceId:string, fabricEnvId:string, executorMin:string, executorMax:string, isHighConcurrencyEnabled:string, properties:string, EventProcessedUtcTime:datetime, PartitionId:long, EventEnqueuedUtcTime:datetime) 
.alter column AllSparkLogs.['timestamp'] policy encoding type = 'SpreadNumeric'
